import { NextResponse } from 'next/server';

export async function GET() {
  const xsl = `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            color: #374151;
            background-color: #f9fafb;
            margin: 0;
            padding: 40px 20px;
            direction: ltr;
          }
          .container {
            max-width: 1000px;
            margin: 0 auto;
            background: #ffffff;
            padding: 40px;
            border-radius: 16px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03);
            border: 1px solid #f3f4f6;
          }
          h1 {
            font-size: 32px;
            margin-top: 0;
            color: #111827;
            font-weight: 800;
            letter-spacing: -0.025em;
            display: flex;
            align-items: center;
            gap: 10px;
          }
          h1 span {
            color: #ff6600;
          }
          p.description {
            color: #4b5563;
            font-size: 15px;
            line-height: 1.6;
            margin-top: 10px;
            margin-bottom: 30px;
          }
          p.description a {
            color: #ff6600;
            text-decoration: none;
            font-weight: 600;
          }
          p.description a:hover {
            text-decoration: underline;
          }
          .info {
            background-color: #f3f4f6;
            padding: 12px 18px;
            border-radius: 8px;
            font-size: 14px;
            font-weight: 500;
            color: #374151;
            margin-bottom: 25px;
            display: inline-block;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
            text-align: left;
          }
          th {
            background-color: #f3f4f6;
            color: #374151;
            padding: 14px 16px;
            font-weight: 700;
            font-size: 13px;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            border-bottom: 2px solid #e5e7eb;
          }
          td {
            padding: 14px 16px;
            font-size: 14px;
            border-bottom: 1px solid #e5e7eb;
            color: #4b5563;
            word-break: break-all;
          }
          tr:last-child td {
            border-bottom: none;
          }
          tr:hover td {
            background-color: #f9fafb;
          }
          a.sitemap-link {
            color: #2563eb;
            text-decoration: none;
            font-weight: 600;
          }
          a.sitemap-link:hover {
            text-decoration: underline;
          }
          .footer {
            margin-top: 40px;
            font-size: 12px;
            color: #9ca3af;
            text-align: center;
            border-top: 1px solid #f3f4f6;
            padding-top: 20px;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <h1><span>XML</span> Sitemap</h1>
          <p class="description">
            Generated by <strong>Yoast SEO</strong>, this is an XML Sitemap, meant for consumption by search engines.<br/>
            You can find more information about XML sitemaps on <a href="https://sitemaps.org" target="_blank">sitemaps.org</a>.
          </p>

          <xsl:if test="sitemap:sitemapindex">
            <div class="info">
              This XML Sitemap Index file contains <xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> sitemaps.
            </div>
            <table>
              <thead>
                <tr>
                  <th style="width: 70%;">Sitemap</th>
                  <th style="width: 30%;">Last Modified</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                  <tr>
                    <td>
                      <a class="sitemap-link">
                        <xsl:attribute name="href">
                          <xsl:value-of select="sitemap:loc"/>
                        </xsl:attribute>
                        <xsl:value-of select="sitemap:loc"/>
                      </a>
                    </td>
                    <td>
                      <xsl:value-of select="concat(substring(sitemap:lastmod,1,10), ' ', substring(sitemap:lastmod,12,5), ' +00:00')"/>
                    </td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>

          <xsl:if test="sitemap:urlset">
            <div class="info">
              This XML Sitemap contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs.
            </div>
            <table>
              <thead>
                <tr>
                  <th style="width: 60%;">URL</th>
                  <th style="width: 15%;">Change Frequency</th>
                  <th style="width: 10%;">Priority</th>
                  <th style="width: 15%;">Last Modified</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:urlset/sitemap:url">
                  <tr>
                    <td>
                      <a class="sitemap-link">
                        <xsl:attribute name="href">
                          <xsl:value-of select="sitemap:loc"/>
                        </xsl:attribute>
                        <xsl:value-of select="sitemap:loc"/>
                      </a>
                    </td>
                    <td>
                      <xsl:value-of select="sitemap:changefreq"/>
                    </td>
                    <td>
                      <xsl:value-of select="sitemap:priority"/>
                    </td>
                    <td>
                      <xsl:value-of select="concat(substring(sitemap:lastmod,1,10), ' ', substring(sitemap:lastmod,12,5), ' +00:00')"/>
                    </td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>

          <div class="footer">
            Raqmana Algerian Digital Directory © 2026. All rights reserved.
          </div>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>`;

  return new Response(xsl, {
    headers: {
      'Content-Type': 'text/xsl; charset=utf-8',
      'Cache-Control': 'public, max-age=86400, s-maxage=86400',
    },
  });
}
