import { getAllArticlesMerged } from '@/lib/custom-articles-store';

export const revalidate = 1800;

export async function GET() {
  const baseUrl = 'https://www.raqmanadz.com';
  const articles = getAllArticlesMerged();

  const now = Date.now();
  const FORTY_EIGHT_HOURS = 48 * 60 * 60 * 1000;

  // Filter articles generated or published in last 48 hours, or all active guides
  let relevantArticles = Object.entries(articles).filter(([_, article]) => {
    const generatedAt = (article as any).generatedAt ? new Date((article as any).generatedAt).getTime() : null;
    if (generatedAt && (now - generatedAt) <= FORTY_EIGHT_HOURS) return true;
    if ((article as any).isTrendingTopic || (article as any).autoGenerated) return true;
    return false;
  });

  // Fallback to top recent articles if none in 48h
  if (relevantArticles.length === 0) {
    relevantArticles = Object.entries(articles).slice(-5);
  }

  const entries = relevantArticles
    .map(([slug, article]) => {
      const pubDate = (article as any).generatedAt ? new Date((article as any).generatedAt).toISOString() : new Date().toISOString();
      const title = article.title
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&apos;');
      return `  <url>
    <loc>${baseUrl}/articles/${slug}</loc>
    <news:news>
      <news:publication>
        <news:name>رقمنة الجزائر</news:name>
        <news:language>ar</news:language>
      </news:publication>
      <news:publication_date>${pubDate}</news:publication_date>
      <news:title>${title}</news:title>
    </news:news>
  </url>`;
    })
    .join('\n');

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:news="http://www.google.com/schemas/sitemap-news/0.9">
${entries}
</urlset>`;

  return new Response(xml, {
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
      'Cache-Control': 'public, max-age=300, s-maxage=900',
    },
  });
}
