/**
 * indexing-process.js — توليد Sitemap وفهرسة Google/IndexNow
 * ===========================================================
 * الاستخدام:
 *   node scripts/news-automation/indexing-process.js
 */

'use strict';

const fs = require('fs');
const path = require('path');
const https = require('https');
const crypto = require('crypto');

// ─── تحميل متغيرات البيئة ─────────────────────────────────────
const ROOT_DIR = path.join(__dirname, '../..');
const envPath = path.join(ROOT_DIR, '.env.local');
if (fs.existsSync(envPath)) {
  fs.readFileSync(envPath, 'utf8').split('\n').forEach((line) => {
    const match = line.match(/^\s*([A-Za-z0-9_]+)\s*=\s*"?([^"\r\n]+)"?/);
    if (match && !process.env[match[1]]) process.env[match[1]] = match[2].trim();
  });
}

const CONFIG = {
  BASE_URL: 'https://www.raqmanadz.com',
  INDEXNOW_KEY: 'raqmana2026indexnowkey789',
  ARTICLES_JSON: path.join(ROOT_DIR, 'lib', 'custom-articles-data.json'),
  SITEMAP_DIR: path.join(ROOT_DIR, 'public'),
  STATE_FILE: path.join(__dirname, '..', 'indexing-state.json'),
  GOOGLE_DAILY_LIMIT: 180,
  SERVICE_ACCOUNT: path.join(ROOT_DIR, 'service-account.json'),
};

// ─── 1. استخراج جميع URLs المقالات الآلية ─────────────────────
function getAutoArticleUrls() {
  const urls = [];
  try {
    const data = JSON.parse(fs.readFileSync(CONFIG.ARTICLES_JSON, 'utf8'));
    Object.keys(data).forEach((slug) => {
      if (data[slug].autoGenerated) {
        urls.push({
          url: `${CONFIG.BASE_URL}/articles/${slug}`,
          lastmod: data[slug].generatedAt || new Date().toISOString(),
          changefreq: 'weekly',
          priority: '0.8',
        });
      }
    });
  } catch {}
  return urls;
}

// ─── 2. توليد Sitemap XML ─────────────────────────────────────
function generateNewsSitemap(urls) {
  if (urls.length === 0) {
    console.log('   ℹ لا توجد مقالات آلية لإضافتها في Sitemap.');
    return null;
  }

  const urlEntries = urls
    .map(
      ({ url, lastmod, changefreq, priority }) => `
  <url>
    <loc>${url}</loc>
    <lastmod>${lastmod.split('T')[0]}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`
    )
    .join('');

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:news="http://www.google.com/schemas/sitemap-news/0.9">
${urlEntries}
</urlset>`;

  const sitemapPath = path.join(CONFIG.SITEMAP_DIR, 'auto-news-sitemap.xml');
  fs.writeFileSync(sitemapPath, xml, 'utf8');
  console.log(`   ✅ تم توليد Sitemap: ${sitemapPath} (${urls.length} رابط)`);
  return sitemapPath;
}

// ─── 3. IndexNow للمقالات الجديدة ─────────────────────────────
function submitIndexNow(urls) {
  return new Promise((resolve) => {
    const urlList = urls.map((u) => u.url);
    if (urlList.length === 0) return resolve({ success: true, skipped: true });

    const payload = JSON.stringify({
      host: 'www.raqmanadz.com',
      key: CONFIG.INDEXNOW_KEY,
      keyLocation: `${CONFIG.BASE_URL}/${CONFIG.INDEXNOW_KEY}.txt`,
      urlList,
    });

    const req = https.request(
      {
        hostname: 'api.indexnow.org',
        path: '/indexnow',
        method: 'POST',
        headers: {
          'Content-Type': 'application/json; charset=utf-8',
          'Content-Length': Buffer.byteLength(payload),
        },
      },
      (res) => {
        let body = '';
        res.on('data', (d) => (body += d));
        res.on('end', () =>
          resolve({ success: res.statusCode === 200 || res.statusCode === 202, statusCode: res.statusCode })
        );
      }
    );
    req.on('error', (e) => resolve({ success: false, error: e.message }));
    req.write(payload);
    req.end();
  });
}

// ─── 4. Google Indexing API (JWT Auth) ────────────────────────
function base64UrlEncode(str) {
  return Buffer.from(str).toString('base64').replace(/=/g, '').replace(/\+/g, '-').replace(/\//g, '_');
}

function getGoogleToken(creds) {
  return new Promise((resolve, reject) => {
    const now = Math.floor(Date.now() / 1000);
    const header = { alg: 'RS256', typ: 'JWT' };
    const claim = {
      iss: creds.client_email,
      scope: 'https://www.googleapis.com/auth/indexing',
      aud: 'https://oauth2.googleapis.com/token',
      exp: now + 3600,
      iat: now,
    };
    const signInput = `${base64UrlEncode(JSON.stringify(header))}.${base64UrlEncode(JSON.stringify(claim))}`;
    const signer = crypto.createSign('RSA-SHA256');
    signer.update(signInput);
    signer.end();
    const jwt = `${signInput}.${base64UrlEncode(signer.sign(creds.private_key))}`;
    const postData = `grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion=${jwt}`;

    const req = https.request(
      {
        hostname: 'oauth2.googleapis.com',
        path: '/token',
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded', 'Content-Length': Buffer.byteLength(postData) },
      },
      (res) => {
        let data = '';
        res.on('data', (c) => (data += c));
        res.on('end', () => {
          try {
            const p = JSON.parse(data);
            p.access_token ? resolve(p.access_token) : reject(new Error(data));
          } catch (e) { reject(e); }
        });
      }
    );
    req.on('error', reject);
    req.write(postData);
    req.end();
  });
}

function sendGoogleIndexRequest(token, url) {
  return new Promise((resolve) => {
    const payload = JSON.stringify({ url, type: 'URL_UPDATED' });
    const req = https.request(
      {
        hostname: 'indexing.googleapis.com',
        path: '/v3/urlNotifications:publish',
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
          'Content-Length': Buffer.byteLength(payload),
        },
      },
      (res) => {
        let body = '';
        res.on('data', (d) => (body += d));
        res.on('end', () => resolve({ success: res.statusCode === 200, statusCode: res.statusCode, body }));
      }
    );
    req.on('error', (e) => resolve({ success: false, error: e.message }));
    req.write(payload);
    req.end();
  });
}

// ─── 5. إرسال Sitemap Ping ────────────────────────────────────
function pingSitemaps(sitemapUrl) {
  const encoded = encodeURIComponent(sitemapUrl);
  const targets = [
    `https://www.google.com/ping?sitemap=${encoded}`,
    `https://www.bing.com/ping?sitemap=${encoded}`,
  ];
  targets.forEach((t) => {
    https.get(t, (res) => res.resume()).on('error', () => {});
  });
  console.log('   📡 تم إرسال Ping للـ Sitemap إلى Google و Bing');
}

// ─── 6. الدالة الرئيسية ──────────────────────────────────────
async function main() {
  console.log('\n' + '='.repeat(60));
  console.log('📡 RAQMANA — محرك الفهرسة والـ Sitemap');
  console.log('='.repeat(60) + '\n');

  // أ. جمع URLs المقالات الآلية
  const autoUrls = getAutoArticleUrls();
  console.log(`📦 مقالات آلية مكتشفة: ${autoUrls.length}`);

  // ب. توليد Sitemap
  const sitemapPath = generateNewsSitemap(autoUrls);

  // ج. IndexNow
  console.log('\n⚡ إرسال IndexNow...');
  const indexNowRes = await submitIndexNow(autoUrls);
  if (indexNowRes.skipped) console.log('   ℹ لا توجد روابط جديدة');
  else if (indexNowRes.success) console.log(`   ✅ قُبل الإرسال (HTTP ${indexNowRes.statusCode})`);
  else console.log(`   ⚠ خطأ IndexNow: ${indexNowRes.statusCode || indexNowRes.error}`);

  // د. Google Indexing API
  if (fs.existsSync(CONFIG.SERVICE_ACCOUNT)) {
    console.log('\n🤖 إرسال لـ Google Indexing API...');
    try {
      const creds = JSON.parse(fs.readFileSync(CONFIG.SERVICE_ACCOUNT, 'utf8'));
      const token = await getGoogleToken(creds);

      // تحميل الحالة
      let state = {};
      if (fs.existsSync(CONFIG.STATE_FILE)) {
        try { state = JSON.parse(fs.readFileSync(CONFIG.STATE_FILE, 'utf8')).googleIndexed || {}; } catch {}
      }

      const unindexed = autoUrls.filter((u) => !state[u.url]);
      const batch = unindexed.slice(0, CONFIG.GOOGLE_DAILY_LIMIT);
      console.log(`   📦 دفعة: ${batch.length} رابط`);

      let success = 0;
      let quotaDone = false;
      for (const item of batch) {
        if (quotaDone) break;
        const res = await sendGoogleIndexRequest(token, item.url);
        if (res.success) {
          success++;
          state[item.url] = new Date().toISOString();
          process.stdout.write(`\r   ⏳ ${success}/${batch.length} `);
        } else if (res.statusCode === 429) {
          console.log('\n   🛑 استُنفدت الحصة اليومية. التوقف التلقائي.');
          quotaDone = true;
        }
        if (!quotaDone) await new Promise((r) => setTimeout(r, 200));
      }
      console.log(`\n   ✅ أُرسل ${success} رابط لـ Googlebot`);

      // حفظ الحالة
      const fullState = fs.existsSync(CONFIG.STATE_FILE)
        ? JSON.parse(fs.readFileSync(CONFIG.STATE_FILE, 'utf8'))
        : {};
      fullState.googleIndexed = state;
      fs.writeFileSync(CONFIG.STATE_FILE, JSON.stringify(fullState, null, 2), 'utf8');

    } catch (err) {
      console.log(`   ⚠ تعذّر الاتصال بـ Google API: ${err.message}`);
    }
  } else {
    console.log('\n   ℹ service-account.json غير موجود — تم تخطي Google Indexing API');
  }

  // هـ. Sitemap Ping
  if (sitemapPath) {
    pingSitemaps(`${CONFIG.BASE_URL}/auto-news-sitemap.xml`);
  }

  console.log('\n' + '='.repeat(60));
  console.log('🎉 اكتملت عملية الفهرسة!');
  console.log('='.repeat(60) + '\n');
}

main().catch((err) => {
  console.error('❌ خطأ عام:', err.message);
  process.exit(1);
});
