import * as Lucide from "lucide-react";
import React from "react";

export const categoryPageMap: Record<string, string> = {
  dzds: "/categories/dzds",
  bills: "/categories/bills",
  mobile: "/categories/mobile",
  post: "/categories/post",
  telecom: "/categories/telecom",
  education: "/categories/education",
  university: "/categories/university",
  vocational: "/categories/vocational",
  interior: "/categories/interior",
  aadl: "/categories/aadl",
  enpi: "/categories/enpi",
  tax: "/categories/tax",
  justice: "/categories/justice",
  publicContracts: "/categories/publicContracts",
  realEstate: "/categories/realEstate",
  foreignAffairs: "/categories/foreignAffairs",
  socialSecurity: "/categories/socialSecurity",
  health: "/categories/health",
  vehicles: "/categories/vehicles",
  transport: "/categories/transport",
  employment: "/categories/employment",
  concours: "/jobs",
  commerce: "/categories/commerce",
  customs: "/categories/customs",
  autoEntrepreneur: "/categories/autoEntrepreneur",
  hajj: "/categories/hajj",
  investment: "/categories/investment",
  elections: "/categories/elections",
  police: "/categories/police",
  arpce: "/categories/arpce",
  insurance: "/categories/insurance",
  banking: "/categories/banking",
  agriculture: "/categories/agriculture",
  cnrc: "/categories/cnrc",
  youth: "/categories/youth",
  culture: "/categories/culture",
  tourism: "/categories/tourism",
  water: "/categories/water",
  industry: "/categories/industry",
  environment: "/categories/environment",
  media: "/categories/media",
  finance: "/categories/finance",
  retirement: "/categories/retirement",
};

export const iconMap: Record<string, React.ElementType> = {
  MonitorSmartphone: Lucide.MonitorSmartphone,
  Scale: Lucide.Scale,
  Heart: Lucide.Heart,
  GraduationCap: Lucide.GraduationCap,
  Banknote: Lucide.Banknote,
  Car: Lucide.Car,
  Home: Lucide.Home,
  Briefcase: Lucide.Briefcase,
  Users: Lucide.Users,
  Wifi: Lucide.Wifi,
  Building2: Lucide.Building2,
  ShoppingBag: Lucide.ShoppingBag,
  Wheat: Lucide.Wheat,
  Receipt: Lucide.Receipt,
  Smartphone: Lucide.Smartphone,
  Mail: Lucide.Mail,
  School: Lucide.School,
  Wrench: Lucide.Wrench,
  Building: Lucide.Building,
  FileText: Lucide.FileText,
  Landmark: Lucide.Landmark,
  Globe: Lucide.Globe,
  Shield: Lucide.Shield,
  Plane: Lucide.Plane,
  Package: Lucide.Package,
  UserCheck: Lucide.UserCheck,
  Moon: Lucide.Moon,
  TrendingUp: Lucide.TrendingUp,
  Vote: Lucide.Vote,
  ShieldCheck: Lucide.ShieldCheck,
  Radio: Lucide.Radio,
  ShieldPlus: Lucide.ShieldPlus,
  Leaf: Lucide.Leaf,
  Droplets: Lucide.Droplets,
  Sparkles: Lucide.Sparkles,
  Wallet: Lucide.Wallet,
  ClipboardList: Lucide.ClipboardList,
};
