import { getAllArticlesMerged } from '@/lib/custom-articles-store';

export async function GET() {
  const baseUrl = 'https://www.raqmanadz.com';
  const articles = getAllArticlesMerged();
  const now = new Date().toISOString();

  // Articles index page
  const indexEntry = `  <url>
    <loc>${baseUrl}/articles</loc>
    <lastmod>${now}</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.9</priority>
  </url>`;

  // Individual article pages — lastmod حقيقي من تاريخ إنشاء المقال
  const articleEntries = Object.entries(articles)
    .map(([slug, article]: [string, any]) => {
      const rawDate = article.generatedAt || article.publishedAt || null;
      const lastmod = rawDate ? new Date(rawDate).toISOString() : now;
      // المقالات الآلية تتحدث أسبوعياً، اليدوية شهرياً
      const changefreq = article.autoGenerated ? 'weekly' : 'monthly';
      // أولوية أعلى للمقالات اليدوية المحررة بعناية
      const priority = article.autoGenerated ? '0.7' : '0.8';
      return `  <url>
    <loc>${baseUrl}/articles/${slug}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`;
    })
    .join('\n');

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/sitemap.xsl"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${indexEntry}
${articleEntries}
</urlset>`;

  return new Response(xml, {
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
      'Cache-Control': 'public, max-age=3600, s-maxage=86400',
    },
  });
}
